In [124]:
import pandas as pd

In [125]:
import matplotlib as mpl

In [126]:
import numpy as np

In [127]:
pd.read_csv("county_salaries_2018.csv")

,Name,Employment Status,Ethnic Code,Gender,Department,Job Title,Date Started,Cur Pos Date,Date Term.,Pay Status,...,Bonus $,Wellness Day,Cert Bonus,Contract Bonus,Hlth Waiver,Longevity,Wellnes Bonus,Weekend Bonus,Gross Pay,TOTAL
0,Catherine Abalo,Full-time Regular,Black,Female,Kane Regional Centers,Nursing Assistant,4/8/2010,4/3/2016,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$69,027.34","$68,453.92"
1,Joy M Abbott,Full-time Regular,White (Not of Hispanic Origin),Female,Kane Regional Centers,Cook,2/14/1999,2/14/1999,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$48,058.35","$47,188.74"
2,Kevin J Abbott,Part Time Regular,White (Not of Hispanic Origin),Male,Emergency Management,Fire Instructor - Part Time,6/11/2018,6/11/2018,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$241.50,"$30,576.00"
3,Ryan Robert Abbott,Full-time Regular,White (Not of Hispanic Origin),Male,Sheriff,Deputy Sheriff,8/21/2017,8/21/2017,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$44,542.97","$49,669.69"
4,Jerome J Abmayr,Full-time Regular,White (Not of Hispanic Origin),Male,Facilities Management,Foreman Building Maintenance,5/10/2010,12/30/2012,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$46,806.31","$42,032.80"
5,Jasmine Abram,Full-time Regular,Black,Female,Shuman Center,Childcare Worker,5/31/2016,5/31/2016,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$51,771.78","$51,721.04"
6,Gwendolyn S Abramovitz,Full-time Regular,Black,Female,Administrative Services,Manager Registration,12/31/2000,10/21/2012,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$46,865.44","$46,990.51"
7,Karen D Abrams,Terminated,Black,Female,Human Services,Child Welfare Aide,6/11/1990,6/11/1990,11/25/2018,Terminated,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$31,308.81","$39,272.06"
8,Anthony A Aches,Full-time Regular,White (Not of Hispanic Origin),Male,Police,Police Officer,7/25/1994,1/1/2017,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$120,916.71","$120,067.72"
9,Michael B Acheson,Full-time Regular,White (Not of Hispanic Origin),Male,Administrative Services,Support Specialist,8/22/2016,8/22/2016,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$9,585.32","$33,292.69"
10,Christian M Achilles,Terminated,White (Not of Hispanic Origin),Male,Parks,Seasonal Aide,7/5/2018,7/5/2018,9/4/2018,Terminated,...,$137.50,$0.00,$0.00,$137.50,$0.00,$0.00,$0.00,$0.00,"$3,300.00","$28,979.00"
11,Kiara N Aciescott,Full-time Regular,Black,Female,Kane Regional Centers,Food Service Worker,8/23/2015,8/23/2015,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$50,166.02","$48,823.90"
12,Jeremy G Acker,Full-time Regular,White (Not of Hispanic Origin),Male,Kane Regional Centers,Rn Resident Care Coordinator,9/22/2014,2/7/2016,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$91,389.73","$87,338.52"
13,Suzanne J Acrie,Full-time Regular,White (Not of Hispanic Origin),Female,Human Services,Clerk Typist 1,9/17/2018,9/17/2018,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$8,291.27","$31,657.39"
14,Emily E Adamczyk,Terminated,White (Not of Hispanic Origin),Female,Parks,Seasonal Aide,11/15/2017,11/15/2017,3/20/2018,Terminated,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$344.00,"$19,968.00"
15,Mary E Adamczyk,Full-time Regular,White (Not of Hispanic Origin),Female,County Solicitor,Assistant County Solicitor,7/2/2001,1/29/2012,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$51,196.60","$51,196.08"
16,John V Adams Iii,Full-time Regular,White (Not of Hispanic Origin),Male,Parks,Acting Foreman,7/6/2015,11/13/2016,NaN,Active,...,$147.80,$147.80,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$47,130.39","$43,447.72"
17,Cynthia J Adams,Full-time Regular,Black,Female,District Attorney,Systems Manager,3/12/1979,3/12/1979,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$72,893.60","$72,892.35"
18,Joshua D Adams,Terminated,Black,Male,Facilities Management,Custodial Worker,12/23/2013,12/23/2013,11/23/2018,Terminated,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$35,170.74","$36,121.07"
19,Ty Adams,Intern,Black,Male,Human Services,Student Intern,5/14/2018,5/14/2018,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$9,486.00","$24,960.00"
20,Jacqueline M Adamson,Full-time Regular,White (Not of Hispanic Origin),Female,Treasurer,Computer Operator,3/17/2008,7/13/2015,NaN,Active,...,$140.52,$140.52,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$41,254.52","$39,884.03"
21,Angelia G Adediran,Full-time Regular,Black,Female,Human Services,Dep Dir Office Of Admin,9/17/2018,9/17/2018,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$30,961.68","$115,000.08"
22,Catherine Adekoya,Full-time Regular,Black,Female,Human Services,Adm Fiscal Integrated Systems,3/22/1993,6/14/2015,NaN,REDACTED,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$85,202.06","$85,203.04"
23,Joseph Adu-Marfo,Full-time Regular,Black,Male,Facilities Management,Stationary Engineer,5/19/2014,5/19/2014,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$50,148.89","$49,318.56"
24,Ethan E Affolder,Full-time Regular,White (Not of Hispanic Origin),Male,Parks,Facilities Manager,9/17/2017,9/17/2017,NaN,Active,...,$137.31,$137.31,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$35,699.87","$35,974.49"
25,Susan M Ahearn,Full-time Regular,White (Not of Hispanic Origin),Female,Kane Regional Centers,Nursing Assistant,1/14/1980,1/14/1980,NaN,Active,...,$575.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$450.00,"$52,968.06","$50,059.39"
26,Michael M Ahwesh,Full-time Regular,White (Not of Hispanic Origin),Male,District Attorney,Assistant District Attorney,2/21/2017,2/21/2017,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$19,575.48","$40,553.97"
27,Catherine H Aikens,Intern,White (Not of Hispanic Origin),Female,District Attorney,Legal Intern,10/15/2018,10/15/2018,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$1,069.39","$15,080.00"
28,Amila Ajdinovic,Full-time Regular,White (Not of Hispanic Origin),Female,Kane Regional Centers,Food Service Worker,12/12/2016,12/12/2016,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$48,028.79","$46,771.30"
29,Hafeez A Ajenifuja,Full-time Regular,White (Not of Hispanic Origin),Male,Health,Air Quality Engineer,9/2/2008,1/1/2016,NaN,Active,...,$261.16,$261.16,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$67,901.60","$68,423.30"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6799,Craig H Zinsser,Full-time Regular,White (Not of Hispanic Origin),Male,Parks,Acting Foreman,9/1/1994,4/5/2015,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$51,768.07","$47,869.25"
6800,Earl J Zinsser,Full-time Regular,White (Not of Hispanic Origin),Male,Jail,Correctional Officer,6/8/1987,6/8/1987,NaN,REDACTED,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$79,603.58","$85,035.61"
6801,Daniel J Ziober,Full-time Regular,White (Not of Hispanic Origin),Male,District Attorney,Systems Technician,7/18/2011,9/25/2011,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$48,684.92","$48,684.69"
6802,Amie J Ziots,Full-time Regular,White (Not of Hispanic Origin),Female,Emergency Management,Telecommunication Officer,7/25/2016,7/25/2016,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$51,957.88","$51,305.88"
6803,Stephanie Zipay,Full-time Regular,Black,Female,Jail,Substance Abuse Counselor,8/26/2015,8/26/2015,NaN,Active,...,$500.00,$0.00,$0.00,$0.00,$0.00,$375.00,$125.00,$0.00,"$47,956.48","$48,200.78"
6804,Barbara A Zirngibl,Full-time Regular,White (Not of Hispanic Origin),Female,Health,Environmental Health Specialst,8/28/1989,8/28/1989,NaN,Active,...,$209.65,$209.65,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$56,375.40","$54,929.03"
6805,Virginia M. Zirpoli,Full-time Regular,White (Not of Hispanic Origin),Female,Administrative Services,Data Clerk,11/8/1999,4/15/2018,NaN,Active,...,$134.32,$134.32,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$34,609.21","$35,192.88"
6806,Mark A Zivkovich,Full-time Regular,White (Not of Hispanic Origin),Male,Human Services,Caseworker - Aging (Lng Step),7/17/1989,3/13/2011,NaN,Active,...,$244.25,$244.25,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$66,649.10","$64,152.66"
6807,Craig M Zmenkowski,Full-time Regular,White (Not of Hispanic Origin),Male,Facilities Management,Tuck Pointer,5/2/2016,5/2/2016,NaN,Active,...,$209.05,$209.05,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$58,248.46","$58,313.08"
6808,Trisha V Znosko,Part Time Regular,White (Not of Hispanic Origin),Female,Kane Regional Centers,Per Diem Nursing Assistant,8/27/2012,5/3/2015,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$720.00,"$29,120.00"
6809,Daniel T Zoldos,Full-time Regular,White (Not of Hispanic Origin),Male,Health,Laboratory Technician Off Step,10/3/2016,7/1/2018,NaN,Active,...,$123.11,$123.11,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$33,101.10","$32,347.47"
6810,Albert A Zoller,Full-time Regular,White (Not of Hispanic Origin),Male,Jail,Correctional Officer,6/8/1997,3/11/2012,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$117,813.68","$119,817.53"
6811,Kimberly A Zombeck,Full-time Regular,White (Not of Hispanic Origin),Female,Court Records,Assistant Division Manager,7/25/2011,6/25/2017,NaN,Active,...,$259.38,$259.38,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$67,438.80","$67,958.60"
6812,Maureen Zombeck,Full-time Regular,White (Not of Hispanic Origin),Female,Kane Regional Centers,Licensed Practical Nurse,12/10/2018,12/10/2018,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$1,632.40","$42,443.44"
6813,Madison E Zombek,Terminated,White (Not of Hispanic Origin),Female,Parks,Seasonal Aide,4/17/2018,4/17/2018,9/4/2018,Terminated,...,$202.75,$0.00,$0.00,$202.75,$0.00,$0.00,$0.00,$0.00,"$4,866.00","$29,109.50"
6814,Sharon Zorich,Full-time Regular,White (Not of Hispanic Origin),Female,Kane Regional Centers,Food Service Worker,9/4/2018,9/4/2018,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$1,697.62","$23,708.81"
6815,Alyssa M Zottola,Terminated,White (Not of Hispanic Origin),Female,District Attorney,Legal Intern,9/18/2017,9/18/2017,8/7/2018,Terminated,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$4,107.14","$7,540.00"
6816,David M Zottola,Full-time Regular,White (Not of Hispanic Origin),Male,Parks,Acting Foreman,8/16/1994,4/5/2015,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$45,348.80","$42,428.95"
6817,Matthew A Zottola,Full-time Regular,White (Not of Hispanic Origin),Male,Facilities Management,Tuck Pointer,5/5/2014,5/5/2014,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$59,174.58","$58,117.10"
6818,Phillip A. Zottola,Full-time Regular,White (Not of Hispanic Origin),Male,Treasurer,Re Tax System Application Sup,9/25/2000,4/9/2012,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$67,464.44","$67,539.68"
6819,Francis M Zovko,Terminated,White (Not of Hispanic Origin),Male,District Attorney,It Systems Supervisor,12/28/2015,12/28/2015,1/5/2018,Terminated,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$6,855.02","$63,654.03"
6820,David A. Zozom,Full-time Regular,White (Not of Hispanic Origin),Male,Parks,Laborer,6/23/2003,4/5/2015,NaN,Active,...,$150.76,$150.76,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$15,503.39","$39,498.70"
6821,Ryan T Zulka,Full-time Regular,White (Not of Hispanic Origin),Male,Facilities Management,Stationary Engineer,6/15/2015,6/15/2015,NaN,Active,...,$189.65,$189.65,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$55,180.61","$54,464.18"
6822,Stanley J Zunic,Full-time Regular,White (Not of Hispanic Origin),Male,Kane Regional Centers,Acting Compactor,2/7/2016,2/7/2016,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$31,145.05","$30,102.27"
6823,Albert Zupancic,Full-time Regular,White (Not of Hispanic Origin),Male,Public Works Operating,Regional Maintenance Sprv,8/21/2017,8/21/2017,NaN,Active,...,$213.69,$213.69,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$55,504.91","$55,987.72"
6824,Ilan Zur,Full-time Regular,White (Not of Hispanic Origin),Male,District Attorney,Deputy District Attorney,10/5/1998,5/20/2013,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$100,050.72","$100,050.70"
6825,Jeffrey M. Zurisko,Full-time Regular,White (Not of Hispanic Origin),Male,District Attorney,Attorney 4,11/20/2006,4/2/2018,NaN,Active,...,"$1,500.00",$0.00,$0.00,$0.00,"$1,500.00",$0.00,$0.00,$0.00,"$49,591.15","$50,841.92"
6826,Mary E Zusinas,Full-time Regular,White (Not of Hispanic Origin),Female,Public Works Operating,Administrative Assistant,5/20/2013,5/20/2013,NaN,Active,...,$123.75,$123.75,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$32,082.31","$32,422.60"
6827,Parker C Zvejnieks,Terminated,White (Not of Hispanic Origin),Male,Parks,Seasonal Aide,5/31/2018,5/31/2018,9/3/2018,Terminated,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$1,112.89","$18,096.00"
6828,Stephen Zvolensky,Full-time Regular,White (Not of Hispanic Origin),Male,Parks,Regional Park Maintenance Spv,5/13/1985,2/5/2017,NaN,Active,...,$208.16,$208.16,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$54,121.60","$54,537.92"

In [128]:
countysal = pd.read_csv("county_salaries_2018.csv")

In [129]:
countysal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6829 entries, 0 to 6828
Data columns (total 24 columns):
Name                 6829 non-null object
Employment Status    6829 non-null object
Ethnic Code          6829 non-null object
Gender               6829 non-null object
Department           6829 non-null object
Job Title            6828 non-null object
Date Started         6829 non-null object
Cur Pos Date         6829 non-null object
Date Term.           1115 non-null object
Pay Status           6829 non-null object
Annual Salary        6829 non-null object
Overtime $           6829 non-null object
Overtime Hrs.        6829 non-null object
Overtime Rate        6829 non-null object
Bonus $              6829 non-null object
Wellness Day         6829 non-null object
Cert Bonus           6829 non-null object
Contract Bonus       6829 non-null object
Hlth Waiver          6829 non-null object
Longevity            6829 non-null object
Wellnes Bonus        6829 non-null object
Weekend Bonus        6829 non-null object
Gross Pay            6829 non-null object
TOTAL                6829 non-null object
dtypes: object(24)
memory usage: 1.3+ MB

In [130]:
countysal.rename(columns={'Name':'name'}, inplace=True)

In [131]:
countysal.rename(columns={'Employment Status':'status'}, inplace=True)
countysal.rename(columns={'Ethnic Code':'race'}, inplace=True)
countysal.rename(columns={'Gender':'sex'}, inplace=True)
countysal.rename(columns={'Department':'dept'}, inplace=True)
countysal.rename(columns={'Job Title':'job_title'}, inplace=True)
countysal.rename(columns={'Date Started':'date_started'}, inplace=True)
countysal.rename(columns={'Cur Pos Date':'current_position_start'}, inplace=True)
countysal.rename(columns={'Date Term.':'date_terminated'}, inplace=True)
countysal.rename(columns={'Pay Status':'pay_status'}, inplace=True)
countysal.rename(columns={'Annual Salary':'salary'}, inplace=True)
countysal.rename(columns={'Overtime $':'overtime'}, inplace=True)
countysal.rename(columns={'Overtime Hrs.':'overtime_hours'}, inplace=True)
countysal.rename(columns={'Overtime Rate':'overtime_rate'}, inplace=True)
countysal.rename(columns={'Bonus $':'bonus'}, inplace=True)
countysal.rename(columns={'Wellness Day':'wellness_day'}, inplace=True)
countysal.rename(columns={'Cert Bonus':'cert_bonus'}, inplace=True)
countysal.rename(columns={'Contract Bonus':'contract_bonus'}, inplace=True)
countysal.rename(columns={'Hlth Waiver':'health_waiver'}, inplace=True)
countysal.rename(columns={'Longevity':'longevity'}, inplace=True)
countysal.rename(columns={'Wellnes Bonus':'wellness_bonus'}, inplace=True)
countysal.rename(columns={'Weekend Bonus':'weekend_bonus'}, inplace=True)
countysal.rename(columns={'Gross Pay':'gross'}, inplace=True)
countysal.rename(columns={'TOTAL':'total'}, inplace=True)

In [132]:
countysal.head()

,name,status,race,sex,dept,job_title,date_started,current_position_start,date_terminated,pay_status,...,bonus,wellness_day,cert_bonus,contract_bonus,health_waiver,longevity,wellness_bonus,weekend_bonus,gross,total
0,Catherine Abalo,Full-time Regular,Black,Female,Kane Regional Centers,Nursing Assistant,4/8/2010,4/3/2016,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$69,027.34","$68,453.92"
1,Joy M Abbott,Full-time Regular,White (Not of Hispanic Origin),Female,Kane Regional Centers,Cook,2/14/1999,2/14/1999,NaN,Active,...,$125.00,$0.00,$0.00,$0.00,$0.00,$0.00,$125.00,$0.00,"$48,058.35","$47,188.74"
2,Kevin J Abbott,Part Time Regular,White (Not of Hispanic Origin),Male,Emergency Management,Fire Instructor - Part Time,6/11/2018,6/11/2018,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$241.50,"$30,576.00"
3,Ryan Robert Abbott,Full-time Regular,White (Not of Hispanic Origin),Male,Sheriff,Deputy Sheriff,8/21/2017,8/21/2017,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$44,542.97","$49,669.69"
4,Jerome J Abmayr,Full-time Regular,White (Not of Hispanic Origin),Male,Facilities Management,Foreman Building Maintenance,5/10/2010,12/30/2012,NaN,Active,...,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,$0.00,"$46,806.31","$42,032.80"

In [133]:
countysal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6829 entries, 0 to 6828
Data columns (total 24 columns):
name                      6829 non-null object
status                    6829 non-null object
race                      6829 non-null object
sex                       6829 non-null object
dept                      6829 non-null object
job_title                 6828 non-null object
date_started              6829 non-null object
current_position_start    6829 non-null object
date_terminated           1115 non-null object
pay_status                6829 non-null object
salary                    6829 non-null object
overtime                  6829 non-null object
overtime_hours            6829 non-null object
overtime_rate             6829 non-null object
bonus                     6829 non-null object
wellness_day              6829 non-null object
cert_bonus                6829 non-null object
contract_bonus            6829 non-null object
health_waiver             6829 non-null object
longevity                 6829 non-null object
wellness_bonus            6829 non-null object
weekend_bonus             6829 non-null object
gross                     6829 non-null object
total                     6829 non-null object
dtypes: object(24)
memory usage: 1.3+ MB

In [134]:
countysal['salary'] = countysal['salary'].str.replace('\$', '')

In [135]:
countysal['overtime'] = countysal['overtime'].str.replace('\$', '')
countysal['overtime_rate'] = countysal['overtime_rate'].str.replace('\$', '')
countysal['bonus'] = countysal['bonus'].str.replace('\$', '')
countysal['wellness_day'] = countysal['wellness_day'].str.replace('\$', '')
countysal['cert_bonus'] = countysal['cert_bonus'].str.replace('\$', '')
countysal['contract_bonus'] = countysal['contract_bonus'].str.replace('\$', '')
countysal['health_waiver'] = countysal['health_waiver'].str.replace('\$', '')
countysal['longevity'] = countysal['longevity'].str.replace('\$', '')
countysal['wellness_bonus'] = countysal['wellness_bonus'].str.replace('\$', '')
countysal['weekend_bonus'] = countysal['weekend_bonus'].str.replace('\$', '')
countysal['gross'] = countysal['gross'].str.replace('\$', '')
countysal['total'] = countysal['total'].str.replace('\$', '')

In [136]:
countysal.head()

,name,status,race,sex,dept,job_title,date_started,current_position_start,date_terminated,pay_status,...,bonus,wellness_day,cert_bonus,contract_bonus,health_waiver,longevity,wellness_bonus,weekend_bonus,gross,total
0,Catherine Abalo,Full-time Regular,Black,Female,Kane Regional Centers,Nursing Assistant,4/8/2010,4/3/2016,NaN,Active,...,125.00,0.00,0.00,0.00,0.00,0.00,125.00,0.00,"69,027.34","68,453.92"
1,Joy M Abbott,Full-time Regular,White (Not of Hispanic Origin),Female,Kane Regional Centers,Cook,2/14/1999,2/14/1999,NaN,Active,...,125.00,0.00,0.00,0.00,0.00,0.00,125.00,0.00,"48,058.35","47,188.74"
2,Kevin J Abbott,Part Time Regular,White (Not of Hispanic Origin),Male,Emergency Management,Fire Instructor - Part Time,6/11/2018,6/11/2018,NaN,Active,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,241.50,"30,576.00"
3,Ryan Robert Abbott,Full-time Regular,White (Not of Hispanic Origin),Male,Sheriff,Deputy Sheriff,8/21/2017,8/21/2017,NaN,Active,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,"44,542.97","49,669.69"
4,Jerome J Abmayr,Full-time Regular,White (Not of Hispanic Origin),Male,Facilities Management,Foreman Building Maintenance,5/10/2010,12/30/2012,NaN,Active,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,"46,806.31","42,032.80"

In [137]:
countysal['salary'] = countysal['salary'].str.replace('\,', '').astype(float)
countysal['overtime'] = countysal['overtime'].str.replace('\,', '').astype(float)
countysal['overtime_rate'] = countysal['overtime_rate'].str.replace('\,', '').astype(float)
countysal['bonus'] = countysal['bonus'].str.replace('\,', '').astype(float)
countysal['wellness_day'] = countysal['wellness_day'].str.replace('\,', '').astype(float)
countysal['cert_bonus'] = countysal['cert_bonus'].str.replace('\,', '').astype(float)
countysal['contract_bonus'] = countysal['contract_bonus'].str.replace('\,', '').astype(float)
countysal['health_waiver'] = countysal['health_waiver'].str.replace('\,', '').astype(float)
countysal['longevity'] = countysal['longevity'].str.replace('\,', '').astype(float)
countysal['wellness_bonus'] = countysal['wellness_bonus'].str.replace('\,', '').astype(float)
countysal['weekend_bonus'] = countysal['weekend_bonus'].str.replace('\,', '').astype(float)
countysal['gross'] = countysal['gross'].str.replace('\,', '').astype(float)
countysal['total'] = countysal['total'].str.replace('\,', '').astype(float)

In [138]:
countysal['overtime_hours'] = countysal['overtime_hours'].str.replace('\,', '').astype(float)

In [139]:
countysal.dtypes

name                       object
status                     object
race                       object
sex                        object
dept                       object
job_title                  object
date_started               object
current_position_start     object
date_terminated            object
pay_status                 object
salary                    float64
overtime                  float64
overtime_hours            float64
overtime_rate             float64
bonus                     float64
wellness_day              float64
cert_bonus                float64
contract_bonus            float64
health_waiver             float64
longevity                 float64
wellness_bonus            float64
weekend_bonus             float64
gross                     float64
total                     float64
dtype: object

In [140]:
countysal.head()

,name,status,race,sex,dept,job_title,date_started,current_position_start,date_terminated,pay_status,...,bonus,wellness_day,cert_bonus,contract_bonus,health_waiver,longevity,wellness_bonus,weekend_bonus,gross,total
0,Catherine Abalo,Full-time Regular,Black,Female,Kane Regional Centers,Nursing Assistant,4/8/2010,4/3/2016,NaN,Active,...,125.0,0.0,0.0,0.0,0.0,0.0,125.0,0.0,69027.34,68453.92
1,Joy M Abbott,Full-time Regular,White (Not of Hispanic Origin),Female,Kane Regional Centers,Cook,2/14/1999,2/14/1999,NaN,Active,...,125.0,0.0,0.0,0.0,0.0,0.0,125.0,0.0,48058.35,47188.74
2,Kevin J Abbott,Part Time Regular,White (Not of Hispanic Origin),Male,Emergency Management,Fire Instructor - Part Time,6/11/2018,6/11/2018,NaN,Active,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,241.50,30576.00
3,Ryan Robert Abbott,Full-time Regular,White (Not of Hispanic Origin),Male,Sheriff,Deputy Sheriff,8/21/2017,8/21/2017,NaN,Active,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,44542.97,49669.69
4,Jerome J Abmayr,Full-time Regular,White (Not of Hispanic Origin),Male,Facilities Management,Foreman Building Maintenance,5/10/2010,12/30/2012,NaN,Active,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46806.31,42032.80

In [141]:
overtime_by_department = countysal.groupby("dept").overtime.sum().reset_index().sort_values("overtime", ascending=False)

In [142]:
overtime_by_department

                       dept    overtime
16    Kane Regional Centers  8369410.45
15                     Jail  8350905.69
10     Emergency Management  3106862.07
21                   Police  2867586.47
14           Human Services  2144320.26
25                  Sheriff  2092816.25
26            Shuman Center   797143.72
23   Public Works Operating   760476.91
11    Facilities Management   563431.82
8         District Attorney   342084.14
20                    Parks   324409.46
18         Medical Examiner   248840.75
12                   Health   101465.90
0   Administrative Services    26878.26
27                Treasurer     1151.21
6          County Solicitor      200.00
1          Budget & Finance        0.00
13          Human Resources        0.00
9      Economic Development        0.00
17              MBE-DBE-WBE        0.00
7             Court Records        0.00
19   Miscellaneous Agencies        0.00
5            County Manager        0.00
22          Public Defender        0.00
4          County Executive        0.00
24        Retirement System        0.00
3            County Council        0.00
2                Controller        0.00

In [143]:
ot_hours_by_dept = countysal.groupby("dept").overtime_hours.sum().reset_index().sort_values("overtime_hours", ascending=False).astype(str)

In [144]:
ot_hours_by_dept

                       dept      overtime_hours
16    Kane Regional Centers            527008.5
15                     Jail            196345.5
10     Emergency Management           126623.25
14           Human Services            74037.15
21                   Police            50376.25
23   Public Works Operating   47207.63999999999
25                  Sheriff            38201.82
26            Shuman Center  35388.909999999996
11    Facilities Management  28366.190000000002
20                    Parks            15128.17
8         District Attorney              7762.5
18         Medical Examiner   6393.709999999999
12                   Health  3205.1300000000006
0   Administrative Services              1009.0
27                Treasurer                52.0
13          Human Resources                1.25
6          County Solicitor                 1.0
1          Budget & Finance                 0.0
9      Economic Development                 0.0
17              MBE-DBE-WBE                 0.0
7             Court Records                 0.0
19   Miscellaneous Agencies                 0.0
5            County Manager                 0.0
22          Public Defender                 0.0
4          County Executive                 0.0
24        Retirement System                 0.0
3            County Council                 0.0
2                Controller                 0.0

In [145]:
avg_ot_rate_by_dept = countysal.groupby("dept").overtime_rate.mean().reset_index().sort_values("overtime_rate", ascending=False).astype(str)

In [146]:
avg_ot_rate_by_dept

                       dept        overtime_rate
21                   Police    47.62085034013608
25                  Sheriff    40.67285714285716
15                     Jail   30.924403927068703
8         District Attorney   25.150653846153844
10     Emergency Management    21.59242424242425
18         Medical Examiner   21.363018867924524
26            Shuman Center   17.483082706766925
16    Kane Regional Centers   16.730618466898925
11    Facilities Management   16.050171673819737
14           Human Services    14.55460111317253
23   Public Works Operating   12.293855421686745
12                   Health    9.187057356608477
6          County Solicitor   3.4482758620689653
20                    Parks    3.129541284403671
0   Administrative Services   2.0982698961937714
27                Treasurer  0.24876404494382023
1          Budget & Finance                  0.0
13          Human Resources                  0.0
17              MBE-DBE-WBE                  0.0
9      Economic Development                  0.0
19   Miscellaneous Agencies                  0.0
7             Court Records                  0.0
5            County Manager                  0.0
22          Public Defender                  0.0
4          County Executive                  0.0
24        Retirement System                  0.0
3            County Council                  0.0
2                Controller                  0.0

In [147]:
ot_by_job = countysal.groupby("job_title").overtime.sum().reset_index().sort_values("overtime", ascending=False).astype(str)

In [148]:
ot_by_job

                          job_title            overtime
298            Correctional Officer   7674006.690000004
880       Telecommunication Officer          2868516.46
635               Nursing Assistant  2493216.5799999987
689                  Police Officer  2293547.5800000005
357                  Deputy Sheriff  1748313.6199999999
194     Caseworker - Cyf (Lng Step)  1354832.8499999987
457             Food Service Worker  1266204.2499999998
553        Licensed Practical Nurse  1151704.2499999998
759                Registered Nurse   774764.3300000002
230                Childcare Worker   619507.1399999999
555                      Lieutenant           611800.11
771    Rn Resident Care Coordinator           554769.58
26                   Acting Foreman   534128.3200000002
481                     Housekeeper  373738.26000000007
390                          Driver  372327.11000000004
25                 Acting Compactor           364537.66
456         Food Service Supervisor           323722.29
172                  Building Guard  322261.14999999985
199           Caseworker Supervisor   274501.2700000001
283                            Cook  271849.18000000005
228              Child Welfare Aide           258339.01
241                  Clerk Typist 1           208979.87
618        Mental Health Specialist           174263.56
774                       Scientist  165320.37000000005
146                      Attorney 3           163952.86
401                     Electrician           136923.15
422          Equipment Operator C1A  135204.52000000002
803                 Shift Commander           122264.22
27      Acting Housekeeping Foreman            108282.5
494     Identification Technician 1  101032.56999999999
..                              ...                 ...
372      Director Of Administration                 0.0
373           Director Of Education                 0.0
374       Director Of Mental Health                 0.0
376      Director S Action Line Mgr                 0.0
349      Deputy Director Recreation                 0.0
348    Deputy Director Pretrial Div                 0.0
347  Deputy Director Post Trial Div                 0.0
346   Deputy Director Of Operations                 0.0
324  Dep Dir Child Youth/Family Srv                 0.0
325    Dep Dir Environmental Health                 0.0
326  Dep Dir Maintenance Operations                 0.0
327   Dep Dir Off Behavioral Health                 0.0
328   Dep Dir Office Communty Relat                 0.0
329         Dep Dir Office Of Admin                 0.0
330   Dep Dir Pub Policy & Comm Rel                 0.0
331    Dep Dir, Off Mr/Dvlp Disabil                 0.0
332   Dep Director Facilities Maint                 0.0
333   Dep Director Operations/Admin                 0.0
335  Dep Treas\Finance & Accounting                 0.0
336  Deputy Chief Informatn Officer                 0.0
337    Deputy Chief Purchas Officer                 0.0
338               Deputy Controller                 0.0
339           Deputy County Manager                 0.0
340    Deputy Dir Juvenile Division                 0.0
341                 Deputy Director                 0.0
342      Deputy Director - Fire/Ems                 0.0
343  Deputy Director Administration                 0.0
344        Deputy Director Chp & Dp                 0.0
345    Deputy Director Fiscal/Admin                 0.0
923                      Writ Clerk                 0.0

[924 rows x 2 columns]

In [149]:
countysal.groupby("job_title").overtime_hours.mean().reset_index().sort_values("overtime_hours", ascending=False).astype(str)

                          job_title      overtime_hours
27      Acting Housekeeping Foreman           1719.8125
157         Bas Tech/Stat Eng Rover             1089.64
481                     Housekeeper             896.675
334    Dep Fire Marshal/K-9 Handler               865.0
473                       Head Cook             830.375
457             Food Service Worker   736.5140186915888
618        Mental Health Specialist              730.25
602                Material Handler               667.6
553        Licensed Practical Nurse   630.8831775700935
163         Bldg Automated Sys Tech              629.32
635               Nursing Assistant   601.7292263610315
468         Graduate Practice Nurse               599.5
456         Food Service Supervisor    597.574074074074
610          Medical Record Trans 1              596.25
422          Equipment Operator C1A   567.1447368421053
537    Lead Bldg Automated Sys Tech             545.315
166            Bombadeer Operations               514.0
405          Emergency 911 Cad Tech               501.0
539                   Lead Engineer            481.0325
759                Registered Nurse  450.63380281690144
283                            Cook           445.65625
880       Telecommunication Officer   429.9425182481752
685              Plumber Supervisor              415.01
390                          Driver   410.7923333333334
298            Correctional Officer  400.72222222222223
230                Childcare Worker   376.7877027027027
25                 Acting Compactor  339.83870967741933
392                     Driver Supv              321.83
771    Rn Resident Care Coordinator               316.5
918                   Warrant Clerk              311.75
..                              ...                 ...
371     Director Community Outreach                 0.0
372      Director Of Administration                 0.0
373           Director Of Education                 0.0
374       Director Of Mental Health                 0.0
348    Deputy Director Pretrial Div                 0.0
347  Deputy Director Post Trial Div                 0.0
346   Deputy Director Of Operations                 0.0
345    Deputy Director Fiscal/Admin                 0.0
323                Dental Hygienist                 0.0
324  Dep Dir Child Youth/Family Srv                 0.0
325    Dep Dir Environmental Health                 0.0
326  Dep Dir Maintenance Operations                 0.0
327   Dep Dir Off Behavioral Health                 0.0
328   Dep Dir Office Communty Relat                 0.0
329         Dep Dir Office Of Admin                 0.0
330   Dep Dir Pub Policy & Comm Rel                 0.0
331    Dep Dir, Off Mr/Dvlp Disabil                 0.0
332   Dep Director Facilities Maint                 0.0
333   Dep Director Operations/Admin                 0.0
335  Dep Treas\Finance & Accounting                 0.0
336  Deputy Chief Informatn Officer                 0.0
337    Deputy Chief Purchas Officer                 0.0
338               Deputy Controller                 0.0
339           Deputy County Manager                 0.0
340    Deputy Dir Juvenile Division                 0.0
341                 Deputy Director                 0.0
342      Deputy Director - Fire/Ems                 0.0
343  Deputy Director Administration                 0.0
344        Deputy Director Chp & Dp                 0.0
923                      Writ Clerk                 0.0

[924 rows x 2 columns]

In [150]:
countysal.groupby(["dept", "overtime"]).overtime_hours.sum().reset_index().sort_values("overtime_hours", ascending=False).astype(str)

                         dept  overtime overtime_hours
2700    Kane Regional Centers  58621.71         6172.0
2697    Kane Regional Centers  52655.36         5374.5
2693    Kane Regional Centers  48164.17        5238.75
2695    Kane Regional Centers  50680.41         5138.0
2692    Kane Regional Centers  46722.89         4900.0
2704    Kane Regional Centers  91698.75         4784.0
2699    Kane Regional Centers  57082.28        4030.75
2682    Kane Regional Centers  39432.83        3903.75
2696    Kane Regional Centers  52330.09        3798.25
2698    Kane Regional Centers  54623.35        3512.25
2662    Kane Regional Centers  31623.67         3474.5
2702    Kane Regional Centers  64987.43         3411.0
2688    Kane Regional Centers  44662.89         3127.0
2691    Kane Regional Centers  46567.76         3098.0
2694    Kane Regional Centers  49125.99         3008.0
2690    Kane Regional Centers   46522.4        2995.75
2683    Kane Regional Centers  40789.22         2990.5
2628    Kane Regional Centers  25284.99        2849.25
2661    Kane Regional Centers  31565.32        2836.25
2664    Kane Regional Centers  31996.94        2799.25
2659    Kane Regional Centers  31286.95        2745.75
2701    Kane Regional Centers  62777.64         2745.0
2646    Kane Regional Centers  28703.44         2650.0
2678    Kane Regional Centers  36857.24         2643.5
2703    Kane Regional Centers  66347.94        2632.25
2642    Kane Regional Centers  28304.24         2597.0
2684    Kane Regional Centers  41271.25        2590.25
2676    Kane Regional Centers  35537.49        2588.75
2667    Kane Regional Centers  32696.49         2584.5
2622    Kane Regional Centers  24174.11        2567.75
...                       ...       ...            ...
1183                     Jail     12.69           0.25
536                    Health       0.0            0.0
1178                     Jail       0.0            0.0
2769   Miscellaneous Agencies       0.0            0.0
2770                    Parks       0.0            0.0
2868                   Police       0.0            0.0
24                 Controller       0.0            0.0
3446            Shuman Center       0.0            0.0
3112          Public Defender       0.0            0.0
647            Human Services       0.0            0.0
648            Human Services      1.42            0.0
649            Human Services      7.76            0.0
3550                Treasurer       0.0            0.0
23           Budget & Finance       0.0            0.0
28           County Solicitor       0.0            0.0
25             County Council       0.0            0.0
26           County Executive       0.0            0.0
27             County Manager       0.0            0.0
30              Court Records       0.0            0.0
31          District Attorney       0.0            0.0
3113   Public Works Operating       0.0            0.0
3292                  Sheriff       0.0            0.0
3291        Retirement System       0.0            0.0
2706         Medical Examiner       0.0            0.0
2705              MBE-DBE-WBE       0.0            0.0
1720    Kane Regional Centers       0.0            0.0
379     Facilities Management       0.0            0.0
80       Economic Development       0.0            0.0
81       Emergency Management       0.0            0.0
0     Administrative Services       0.0            0.0

[3552 rows x 3 columns]

In [151]:
countysal.groupby(["dept"]).overtime_hours.sum()

dept
Administrative Services      1009.00
Budget & Finance                0.00
Controller                      0.00
County Council                  0.00
County Executive                0.00
County Manager                  0.00
County Solicitor                1.00
Court Records                   0.00
District Attorney            7762.50
Economic Development            0.00
Emergency Management       126623.25
Facilities Management       28366.19
Health                       3205.13
Human Resources                 1.25
Human Services              74037.15
Jail                       196345.50
Kane Regional Centers      527008.50
MBE-DBE-WBE                     0.00
Medical Examiner             6393.71
Miscellaneous Agencies          0.00
Parks                       15128.17
Police                      50376.25
Public Defender                 0.00
Public Works Operating      47207.64
Retirement System               0.00
Sheriff                     38201.82
Shuman Center               35388.91
Treasurer                      52.00
Name: overtime_hours, dtype: float64

In [158]:
overtime_table = pd.pivot_table(countysal,index=["dept"],values=["overtime", "overtime_hours"],aggfunc=np.sum).sort_values("overtime", ascending=False).astype(str).round(2)

In [163]:
overtime_table

                                   overtime      overtime_hours
dept
Kane Regional Centers     8369410.449999991            527008.5
Jail                      8350905.690000001            196345.5
Emergency Management     3106862.0700000008           126623.25
Police                   2867586.4699999993            50376.25
Human Services           2144320.2600000007            74037.15
Sheriff                  2092816.2499999995            38201.82
Shuman Center                     797143.72  35388.909999999996
Public Works Operating    760476.9099999998   47207.63999999999
Facilities Management     563431.8200000001  28366.190000000002
District Attorney                 342084.14              7762.5
Parks                     324409.4600000001            15128.17
Medical Examiner         248840.75000000006   6393.709999999999
Health                   101465.90000000001  3205.1300000000006
Administrative Services  26878.260000000002              1009.0
Treasurer                           1151.21                52.0
County Solicitor                      200.0                 1.0
Budget & Finance                        0.0                 0.0
Human Resources                         0.0                1.25
Economic Development                    0.0                 0.0
MBE-DBE-WBE                             0.0                 0.0
Court Records                           0.0                 0.0
Miscellaneous Agencies                  0.0                 0.0
County Manager                          0.0                 0.0
Public Defender                         0.0                 0.0
County Executive                        0.0                 0.0
Retirement System                       0.0                 0.0
County Council                          0.0                 0.0
Controller                              0.0                 0.0